---
name: CD

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Docker Setup [Login]
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
 
      - name: Ensure deployment folder permissions
        run: |
          DEPLOY_DIR=$HOME/app
          mkdir -p $DEPLOY_DIR
          # Give ownership to the runner user
          sudo chown -R $USER:$USER $DEPLOY_DIR
          # Allow read/write/execute for owner, read/execute for group/others
          chmod -R 755 $DEPLOY_DIR

      - name: Sync project to deployment folder
        run: |
          DEPLOY_DIR=$HOME/app
          rsync -av --delete . $DEPLOY_DIR    

      - name: Write .env file
        run: |
          DEPLOY_DIR=$HOME/app
          cat <<EOF > .env
          POSTGRES_CONTAINER_NAME=${{ vars.POSTGRES_CONTAINER_NAME }}
          POSTGRES_IMAGE=${{ vars.POSTGRES_IMAGE }}
          POSTGRES_HOST_PORT=${{ secrets.POSTGRES_HOST_PORT }}
          POSTGRES_CONTAINER_PORT=${{ vars.POSTGRES_CONTAINER_PORT }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          #   DATABASE_URL=${{ secrets.DATABASE_URL }}

          REDIS_CONTAINER_NAME=${{ vars.REDIS_CONTAINER_NAME }}
          REDIS_IMAGE=${{ vars.REDIS_IMAGE }}
          REDIS_HOST_PORT=${{ vars.REDIS_HOST_PORT }}
          REDIS_CONTAINER_PORT=${{ vars.REDIS_CONTAINER_PORT }}
          #   REDIS_URL=${{ secrets.REDIS_URL }}

          BACKEND_CONTAINER_NAME=${{ vars.BACKEND_CONTAINER_NAME }}
          BACKEND_HOST_PORT=${{ secrets.BACKEND_HOST_PORT }}
          BACKEND_CONTAINER_PORT=${{ vars.BACKEND_CONTAINER_PORT }}
          BACKEND_IMAGE=${{ secrets.BACKEND_IMAGE }}
      

          FRONTEND_CONTAINER_NAME=${{ vars.FRONTEND_CONTAINER_NAME }}
          FRONTEND_IMAGE=${{ secrets.FRONTEND_IMAGE }}
          FRONTEND_HOST_PORT=${{ vars.FRONTEND_HOST_PORT }}
          FRONTEND_CONTAINER_PORT=${{ vars.FRONTEND_CONTAINER_PORT }}

          NGINX_CONTAINER_NAME=${{ vars.NGINX_CONTAINER_NAME }}
          NGINX_IMAGE=${{ secrets.NGINX_IMAGE }}
          NGINX_HOST_PORT=${{ vars.NGINX_HOST_PORT }}
          NGINX_CONTAINER_PORT=${{ vars.NGINX_CONTAINER_PORT }}

          # NETWORK_NAME=${{ vars.NETWORK_NAME }}
          EOF    
        
      - name: Run the Deployment of containers with Docker Compose
        run: |
          cd $HOME/app
          docker compose --env-file .env pull
          docker compose --env-file .env up -d --force-recreate --pull always